### ISSUE TITLE
Podłączenie klas "bgmovableobject" oraz "background" do klasy "level"

### ISSUE THREAD

**Issue by Kusoku** [Team-Luna/Engine_IIUJ_Summer_2013#10]
Dostosować Background/bgmovableobject do poprawnego podpięcia do Levelu,
Współpraca: @kusoku @darthwojtek

**Comment by Kusoku** [comment]
BGMovableObject podpięte w pełni, Background jeszcze wymaga poprawek (trzeba podpiąć to jako listę i dopisać do ładowania z pliku)

@darthwojtek

**Comment by darthwojtek** [comment]
done and done
