### ISSUE TITLE
Zaprojektowanie bazowych możliwości sztucznej inteligencji

### ISSUE THREAD

**Issue by Babiuszek** [Team-Luna/Engine_IIUJ_Summer_2013#23]
Różne typy potworów mogą wymagać różnych poziomów sztucznej inteligencji. Potrzeba zdefiniować sposób zaawansowana. Opcjonalnie można zaplanować sztuczną inteligencję boss'a.

Współpraca: @kusoku @Babiuszek

**Comment by Kusoku** [comment]
@kusoku @Babiuszek  kod wykonywany na jednym komputerze
