### ISSUE TITLE
Zaimplementowanie sztucznej inteligencji

### ISSUE THREAD

**Issue by Babiuszek** [Team-Luna/Engine_IIUJ_Summer_2013#35]
Dodanie kodu potrzebnego do wykonania sztucznej inteligencji. Trzeba też zlinkować sztuczną inteligencję do potworów. Generalny debugging.

Współpraca: @kusoku @Babiuszek

**Comment by Kusoku** [comment]
@kusoku @babiuszek (wykonywany kod na jednym komputerze)
