### ISSUE TITLE
Połaczenie klas dotyczących tła, uogólnienie ich oraz poprawne tworzenie obiektów tła.

### ISSUE THREAD

**Issue by Kusoku** [Team-Luna/Engine_IIUJ_Summer_2013#38]
Na początku ręcznie

Współpraca: @darthwojtek @Kusoku

**Comment by Kusoku** [comment]
Objekty BgMovableObject ładowane z pliku, należy zastosować tę samą metode w Background

@darthwojtek

**Comment by darthwojtek** [comment]
gotowe
